import programsRoutes from "./programs.routes";
import configurationRoutes from "./configuration.routes";
import globalConfigRoutes from "./global-config.routes";
import tenantRoutes from "./tenant.routes";
import userMappingRoutes from "./user-mapping.routes";
import hierarchiesRoutes from "./hierarchies.routes";
import currenciesRoutes from "./currencies.routes";
import industriesRoutes from "./labour-category.route";
import userRoutes from "./user.routes";
import timeZoneRoutes from "./time-zones.routes";
import OnboardingConfigurationRoutes from "./onboarding-configuration.route";
import countriesRoutes from "./countries.routes";
import programsConfigRoutes from "./program-config.routes";
import programModuleRoutes from "./program-module.routes";
import moduleRouter from "./module.routes";
import qualificationTypeRouter from "./qualification-type.routes";
import rateTypeRouter from "./rate-type.routes";
import foundationalDataTypeRoutes from "./master-datatypes.routes";
import workLocationRoutes from './work-location.route';
import languageRoutes from './language.routes';
import supportingTextRoutes from './supporting-text.routes';
import holidayCalendarRoutes from "./holiday-calendar-routes";
import feesConfigurationRoute from "./fees-config.route";
import picklistRoutes from "./picklist.routes";
import foundationalDataRoutes from "./master-data-routes";
import WorkflowRoutes from "./workflow.routes";
import customFieldsRoutes from "./custom-fields.routes";
import reasoncodeRoute from "./reason-code-action.routes";
import EventRoutes from "./event.routes";
import passwordPolicyRoutes from "./password-policy.routes";
import vendorDistributionScheduleRoutes from "./vendor-distribution-schedule.routes";
import vendorComplianceDocumentRoutes from "./vendor-compliance-document.routes";
import customFieldsHierarchieRoutes from "./custom-field-hierarchie.routes";
import customFieldLocationRoutes from "./coustom-field-location.routes";
import programVendorRoutes from "./program-vendor.routes";
import vendordocumentsgroup from "./vendor-document-group.route";
import QualificationsRoutes from "./qualifications.routes";
import WorkflowMethodRoutes from "./workflow-methods.routes";
import { FastifyInstance } from "fastify";
import VendorGroupRoutes from "./venodr-group.routes";
import vendorMarkupConfigRoutes from "./vendor-markup-config.routes";
import countyRoutes from "./county.routes";
import stateRoutes from "./state.routes";
import resourceCityRoutes from "./city.route";
import customFieldsMasterDataRoutes from "./custom-field-master-data.routes";
import recipientTypeRoute from "./recipient-types.routes";
import SchemaRoutes from "./schema.routes";
import candidateRoutes from "./candidate.routes";
import shiftTypeRoutes from './shift-type.routes';
import shiftConfigurationRoutes from './shift-configuration.routes';
import WorkflowApproverRoutes from "./workflow-approvers.routes";
import shiftConfigurationHierarchiesRoutes from "./shift-configuration-hierarchies.route";
import vendorComplianceReqDocMappingRoutes from "./vendor-compliance-req-doc-mapping.route";
import fieldOperatorRoutes from "./field-operator.routes";
import WorkflowFieldConfigRoutes from "./workflow-field-config.route";
import WorkflowDataSourceRoute from "./workflow-data-source.route";
import WorkflowFieldRoutes from "./workflow-field.route";
import hierarchyCustomFieldRoutes from "./hierarchies-custom-field.route";
import JobWorkFlowRoutes from "./job-workflow.routes";
import expenseConfigurationRoutes from "./expense-configuration.routes";
import TimesheetExpenseRuleRoutes from "./timesheet-expense-rule.route";
import timesheetTypeConfigRoutes from "./timesheet-type-config.route";
import timesheetExpenseRuleGroupRoutes from "./timesheet-expense-rule-group.route";
import expenseTypeRoute from "./expense-type.routes";
import rateCardsRoutes from "./rate-card.route";
import rateConfigurationsRoutes from "./rate-configurations.route";
import delegationRoutes from "./delegation.route";
import checkListRoutes from "./checklist.routes";
import jobTemplate from "./job-template.routes";
import JobCategoryRoutes from "./job-category.routes";
import invoiceConfigRoute from "./invoice-config.routes";
import checklistRoutes from "./checklist.routes";
import contactUsRoutes from './contactUs.route';
import leaveTypeRoutes from "./leave-type.route";
import sowTemplateRoutes from "./sow_template.route";
import mtpRoutes from "./mtp.routes";
import thresholdRoutes from "./notification-threshold-config.routes";
import rateGuidanceRoutesMaster from './rate-guidance-master.route';
const basePrefix = "/config/v1/api";

export default async function (app: FastifyInstance) {
  app.register(timeZoneRoutes, { prefix: `${basePrefix}` });
  app.register(countriesRoutes, { prefix: `${basePrefix}` });
  app.register(currenciesRoutes, { prefix: `${basePrefix}` });
  app.register(globalConfigRoutes, { prefix: `${basePrefix}` });
  app.register(languageRoutes, { prefix: `${basePrefix}` });
  app.register(moduleRouter, { prefix: `${basePrefix}` });
  app.register(tenantRoutes, { prefix: `${basePrefix}` });
  app.register(programsRoutes, { prefix: `${basePrefix}` });
  app.register(industriesRoutes, { prefix: `${basePrefix}` });
  app.register(programModuleRoutes, { prefix: `${basePrefix}` });
  app.register(EventRoutes, { prefix: `${basePrefix}` });
  app.register(programsConfigRoutes, { prefix: `${basePrefix}` });
  app.register(supportingTextRoutes, { prefix: `${basePrefix}` });
  app.register(passwordPolicyRoutes, { prefix: `${basePrefix}` });
  app.register(hierarchiesRoutes, { prefix: `${basePrefix}` });
  app.register(workLocationRoutes, { prefix: `${basePrefix}` });
  app.register(stateRoutes, { prefix: `${basePrefix}` });
  app.register(SchemaRoutes, { prefix: `${basePrefix}` });
  app.register(holidayCalendarRoutes, { prefix: `${basePrefix}` });
  app.register(countyRoutes, { prefix: `${basePrefix}` });
  app.register(reasoncodeRoute, { prefix: `${basePrefix}` });
  app.register(configurationRoutes, { prefix: `${basePrefix}` });
  app.register(userRoutes, { prefix: `${basePrefix}` });
  app.register(userMappingRoutes, { prefix: `${basePrefix}` });
  app.register(QualificationsRoutes, { prefix: `${basePrefix}` });
  app.register(qualificationTypeRouter, { prefix: `${basePrefix}` });
  app.register(customFieldsMasterDataRoutes, { prefix: `${basePrefix}` });
  app.register(hierarchyCustomFieldRoutes, { prefix: `${basePrefix}` });
  app.register(foundationalDataTypeRoutes, { prefix: `${basePrefix}` });
  app.register(feesConfigurationRoute, { prefix: `${basePrefix}` });
  app.register(foundationalDataRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldsRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldsHierarchieRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldLocationRoutes, { prefix: `${basePrefix}` });
  app.register(picklistRoutes, { prefix: `${basePrefix}` });
  app.register(programVendorRoutes, { prefix: `${basePrefix}` });
  app.register(vendordocumentsgroup, { prefix: `${basePrefix}` });
  app.register(VendorGroupRoutes, { prefix: `${basePrefix}` });
  app.register(vendorMarkupConfigRoutes, { prefix: `${basePrefix}` });
  app.register(vendorDistributionScheduleRoutes, { prefix: `${basePrefix}` });
  app.register(vendorComplianceDocumentRoutes, { prefix: `${basePrefix}` });
  app.register(vendorComplianceReqDocMappingRoutes, { prefix: `${basePrefix}` });
  app.register(shiftConfigurationHierarchiesRoutes, { prefix: `${basePrefix}` });
  app.register(shiftConfigurationRoutes, { prefix: `${basePrefix}` });
  app.register(candidateRoutes, { prefix: `${basePrefix}` });
  app.register(resourceCityRoutes, { prefix: `${basePrefix}` });
  app.register(expenseConfigurationRoutes, { prefix: `${basePrefix}` });
  app.register(TimesheetExpenseRuleRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowMethodRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowApproverRoutes, { prefix: `${basePrefix}` });
  app.register(fieldOperatorRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowFieldConfigRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowDataSourceRoute, { prefix: `${basePrefix}` });
  app.register(WorkflowFieldRoutes, { prefix: `${basePrefix}` });
  app.register(JobWorkFlowRoutes, { prefix: `${basePrefix}` });
  app.register(rateTypeRouter, { prefix: `${basePrefix}` });
  app.register(recipientTypeRoute, { prefix: `${basePrefix}` });
  app.register(shiftTypeRoutes, { prefix: `${basePrefix}` });
  app.register(timesheetTypeConfigRoutes, { prefix: `${basePrefix}/program/:program_id` });
  app.register(timesheetExpenseRuleGroupRoutes, { prefix: `${basePrefix}/program/:program_id` });
  app.register(OnboardingConfigurationRoutes, { prefix: `${basePrefix}` })
  app.register(expenseTypeRoute, { prefix: `${basePrefix}` })
  app.register(rateCardsRoutes, { prefix: `${basePrefix}` })
  app.register(rateConfigurationsRoutes, { prefix: `${basePrefix}` })
  app.register(delegationRoutes, { prefix: `${basePrefix}` })
  app.register(checkListRoutes, { prefix: `${basePrefix}` })
  app.register(jobTemplate, { prefix: `${basePrefix}` });
  app.register(JobCategoryRoutes, { prefix: `${basePrefix}` });
  app.register(invoiceConfigRoute, { prefix: `${basePrefix}` })
  app.register(contactUsRoutes, { prefix: `${basePrefix}` });
  app.register(leaveTypeRoutes, { prefix: `${basePrefix}` });
  app.register(sowTemplateRoutes, { prefix: `${basePrefix}` });
  app.register(mtpRoutes, { prefix: `${basePrefix}` });
  app.register(thresholdRoutes, { prefix: `${basePrefix}` });
  app.register(rateGuidanceRoutesMaster, { prefix: `${basePrefix}` });
}
