import programsRoutes from "./programsRoutes";
import configurationRoutes from "./configuration.routes";
import globalConfigRoutes from "./global-config.routes";
import tenantRoutes from "./tenantRoutes";
import userMappingRoutes from "./usermappingRoutes";
import hierarchiesRoutes from "./hierarchies.routes";
import currenciesRoutes from "./currencies.routes";
import industriesRoutes from "./industries.route";
import userRoutes from "./userRoutes";
import timeZoneRoutes from "./timeZonesRoutes";
import OnboardingConfigurationRoutes from "./onboarding-configuration.route";
import countriesRoutes from "./countries.routes";
import programsConfigRoutes from "./program-config.routes";
import programModuleRoutes from "./programModuleRoutes";
import moduleRouter from "./module.routes";
import qualificationTypeRouter from "./qualification-type.routes";
import rateTypeRouter from "./rateTypeRoutes";
import foundationalDataTypeRoutes from "./foundational-datatypes.routes";
import workLocationRoutes from './workLocationRoute';
import languageRoutes from './language.routes';
import supportingTextRoutes from './supportingTextRoutes';
import holidayCalendarRoutes from "./holiday-calendar-routes";
import feesConfigurationRoute from "./feesConfigRoute";
import picklistRoutes from "./picklistRoutes";
import foundationalDataRoutes from "./foundational-data-routes";
import WorkflowRoutes from "./workflowRoutes";
import customFieldsRoutes from "./custom-fields.routes";
import reasoncodeRoute from "./reasoncodeRoutes";
import EventRoutes from "./event.routes";
import passwordPolicyRoutes from "./password-policy.routes";
import vendorDistributionScheduleRoutes from "./vendorDistributionScheduleRoutes";
import vendorComplianceDocumentRoutes from "./vendorComplianceDocumentRoutes";
import customFieldsHierarchieRoutes from "./custom-field-hierarchie.routes";
import customFieldLocationRoutes from "./coustomFieldLocationRoutes";
import programVendorRoutes from "./program-vendor.routes";
import vendordocumentsgroup from "./vendordocumentgroupRoute";
import QualificationsRoutes from "./qualificationsRoutes";
import WorkflowMethodRoutes from "./workFlowMethodsRoutes";
import { FastifyInstance } from "fastify";
import rateCardRoutes from "./rate-card-configuration.routes";
import rateTypeHierarchyRoutes from "./rateTypeHierarchyRoutes";
import rateTypeJobTemplateRoutes from "./rateTypeJobTemplateRoutes";
import VendorGroupRoutes from "./venodrGroupRoutes";
import vendorMarkupConfigRoutes from "./vendorMarkupConfigRoutes";
import vendorLabourCategoryRoutes from "./vendorLabourCategoriesRoutes";
import vendorWorkLocationMappingRoutes from "./vendorWorkLocationMappingRoutes";
import vendorHieararchyMappingRoutes from "./vendorHieararchyMappingRoutes";
import countyRoutes from "./county.routes";
import stateRoutes from "./stateRoutes";
import resourceCityRoutes from "./city.route";
import customFieldsMasterDataRoutes from "./custom-field-master-data.routes";
import recipientTypeRoute from "./recipientTypesRoutes";
import SchemaRoutes from "./schemaRoutes";
import RateCardmappingRoutes from "./rateCardMappingRoutes";
import candidateRoutes from "./candidateRoute";
import shiftTypeRoutes from './shiftTypeRoutes';
import shiftConfigurationRoutes from './shiftConfigurationRoutes';
import RateTypeCategoryRoutes from "./rate-type-category.routes";
import WorkflowApproverRoutes from "./workflowApproversRoutes";
import shiftConfigurationHierarchiesRoutes from "./shiftConfigurationHierarchiesRoute";
import vendorComplianceReqDocMappingRoutes from "./vendorComplianceReqDocMappingRoute";
import fieldOperatorRoutes from "./field-operator-routes";
import WorkflowFieldConfigRoutes from "./workflowFieldConfigRoute";
import WorkflowDataSourceRoute from "./workflowDataSourceRoute";
import WorkflowFieldRoutes from "./workflowFieldRoute";
import hierarchyCustomFieldRoutes from "./HierarchiesCustomFieldRoute";
import JobWorkFlowRoutes from "./job-workflow.routes";
import expenseConfigurationRoutes from "./expense-configuration.routes";
import TimesheetExpenseRuleRoutes from "./timesheet-expense-rule.route";
import timesheetTypeConfigRoutes from "./timesheet-type-config.route";
import timesheetExpenseRuleGroupRoutes from "./timesheet-expense-rule-group.route";
const basePrefix = "/config/v1/api";

export default async function (app: FastifyInstance) {
  app.register(timeZoneRoutes, { prefix: `${basePrefix}` });
  app.register(countriesRoutes, { prefix: `${basePrefix}/countries` });
  app.register(currenciesRoutes, { prefix: `${basePrefix}` });
  app.register(globalConfigRoutes, { prefix: `${basePrefix}` });
  app.register(languageRoutes, { prefix: `${basePrefix}` });
  app.register(moduleRouter, { prefix: `${basePrefix}` });
  app.register(tenantRoutes, { prefix: `${basePrefix}` });
  app.register(programsRoutes, { prefix: `${basePrefix}` });
  app.register(industriesRoutes, { prefix: `${basePrefix}` });

  app.register(programModuleRoutes, { prefix: `${basePrefix}` });
  app.register(EventRoutes, { prefix: `${basePrefix}` });
  app.register(programsConfigRoutes, { prefix: `${basePrefix}` });
  app.register(supportingTextRoutes, { prefix: `${basePrefix}` });
  app.register(passwordPolicyRoutes, { prefix: `${basePrefix}` });
  app.register(hierarchiesRoutes, { prefix: `${basePrefix}` });
  app.register(workLocationRoutes, { prefix: `${basePrefix}` });
  app.register(stateRoutes, { prefix: `${basePrefix}` });
  app.register(SchemaRoutes, { prefix: `${basePrefix}` });

  app.register(holidayCalendarRoutes, { prefix: `${basePrefix}` });
  app.register(countyRoutes, { prefix: `${basePrefix}` });
  app.register(reasoncodeRoute, { prefix: `${basePrefix}` });
  app.register(configurationRoutes, { prefix: `${basePrefix}/configuration` });
  app.register(userRoutes, { prefix: `${basePrefix}` });
  app.register(userMappingRoutes, { prefix: `${basePrefix}` });
  app.register(QualificationsRoutes, { prefix: `${basePrefix}` });
  app.register(qualificationTypeRouter, { prefix: `${basePrefix}` });
  app.register(customFieldsMasterDataRoutes, { prefix: `${basePrefix}` });

  app.register(hierarchyCustomFieldRoutes, { prefix: `${basePrefix}` });
  app.register(foundationalDataTypeRoutes, { prefix: `${basePrefix}` });
  app.register(feesConfigurationRoute, { prefix: `${basePrefix}` });
  app.register(foundationalDataRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldsRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldsHierarchieRoutes, { prefix: `${basePrefix}` });
  app.register(customFieldLocationRoutes, { prefix: `${basePrefix}` });
  app.register(picklistRoutes, { prefix: `${basePrefix}` });
  app.register(programVendorRoutes, { prefix: `${basePrefix}` });

  app.register(vendordocumentsgroup, { prefix: `${basePrefix}` });
  app.register(VendorGroupRoutes, { prefix: `${basePrefix}` });
  app.register(vendorMarkupConfigRoutes, { prefix: `${basePrefix}` });
  app.register(vendorLabourCategoryRoutes, { prefix: `${basePrefix}` });
  app.register(vendorWorkLocationMappingRoutes, { prefix: `${basePrefix}` });
  app.register(vendorHieararchyMappingRoutes, { prefix: `${basePrefix}` });
  app.register(vendorDistributionScheduleRoutes, { prefix: `${basePrefix}` });
  app.register(vendorComplianceDocumentRoutes, { prefix: `${basePrefix}` });
  app.register(vendorComplianceReqDocMappingRoutes, { prefix: `${basePrefix}` });

  app.register(shiftConfigurationHierarchiesRoutes, { prefix: `${basePrefix}` });
  app.register(shiftConfigurationRoutes, { prefix: `${basePrefix}` });
  app.register(candidateRoutes, { prefix: `${basePrefix}` });
  app.register(resourceCityRoutes, { prefix: `${basePrefix}` });
  app.register(expenseConfigurationRoutes, { prefix: `${basePrefix}` });
  app.register(TimesheetExpenseRuleRoutes, { prefix: `${basePrefix}` });

  app.register(WorkflowRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowMethodRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowApproverRoutes, { prefix: `${basePrefix}` });
  app.register(fieldOperatorRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowFieldConfigRoutes, { prefix: `${basePrefix}` });
  app.register(WorkflowDataSourceRoute, { prefix: `${basePrefix}` });
  app.register(WorkflowFieldRoutes, { prefix: `${basePrefix}` });
  app.register(JobWorkFlowRoutes, { prefix: `${basePrefix}` });

  app.register(rateTypeRouter, { prefix: `${basePrefix}` });
  app.register(rateCardRoutes, { prefix: `${basePrefix}` });
  app.register(rateTypeHierarchyRoutes, { prefix: `${basePrefix}` });
  app.register(rateTypeJobTemplateRoutes, { prefix: `${basePrefix}` });
  app.register(recipientTypeRoute, { prefix: `${basePrefix}` });
  app.register(RateCardmappingRoutes, { prefix: `${basePrefix}` });
  app.register(shiftTypeRoutes, { prefix: `${basePrefix}` });
  app.register(RateTypeCategoryRoutes, { prefix: `${basePrefix}` });
  app.register(timesheetTypeConfigRoutes, { prefix: `${basePrefix}/program/:program_id`});
  app.register(timesheetExpenseRuleGroupRoutes, { prefix: `${basePrefix}/program/:program_id` });
  app.register(OnboardingConfigurationRoutes,{prefix:`${basePrefix}`})
}