export const Permissions = {
  PROGRAM: "srn:vms:config:program",
  HIERARCHY: "srn:vms:config:program:hierarchy",
  WORK_LOCATION: "srn:vms:config:program:wl",
  WORKFLOW: "srn:vms:config:program:workflow",
  SUPPORTING_TEXT: "srn:vms:config:program:st",
  HOLIDAY_CALANDER: "srn:vms:config:program:hc",
  PROGRAM_CONFIGURATION: "srn:vms:config:configurations:pc",
  ACCURACY_CONFIGURATION: "srn:vms:config:configurations:ac",
  FEE_CONFIGURATION: "srn:vms:config:configurations:fc",
  ASSIGNMENT_CONFIGURATION: "srn:vms:config:configurations:assmtc",
  TIMESHEET_EXPENSE_RULE: "srn:vms:config:configurations:ter",
  TIMESHEET_EXPENSE_RULES_GROUP: "srn:vms:config:configurations:terg",
  TIMESHEET_TYPE_CONFIGURATION: "srn:vms:config:configurations:ttc",
  EXPENSE_TYPE: "srn:vms:config:configurations:et",
  EXPENSE_CONFIGURATION: "srn:vms:config:configurations:ec",
  INVOICE_CONFIGURATION: "srn:vms:config:configurations:ic",
  USER: "srn:vms:config:user:users",
  USER_ROLE: "srn:vms:config:user:ur",
  SECURITY_SETTING: "srn:vms:config:user:ss",
  RATE_TYPE: "srn:vms:config:rate:rt",
  RATE_CONFIGURATION: "srn:vms:config:rate:rc",
  RATE_CARD: "srn:vms:config:rate:rcd",
  SHIFT_TYPE: "srn:vms:config:shift:st",
  SHIFT_CONFIGURATION: "srn:vms:config:shift:sc",
  QUALIFICATION: "srn:vms:config:job:qualification:q",
  JOB_TEMPLATE: "srn:vms:config:job:jt",
  CUSTOM_FIELD: "srn:vms:config:dm:cf",
  RESON_CODE: "srn:vms:config:dm:rc",
  PICKLIST: "srn:vms:config:dm:picklists",
  LABOUR_CATEGORY: "srn:vms:config:dm:lc",
  VENDOR_INVITE: "srn:vms:config:vendormanagement:vi",
  VENDOR: "srn:vms:config:vendormanagement:v",
  VENDOR_COMPLIANCE: "srn:vms:config:vendormanagement:vc",
  VENDOR_GROUP: "srn:vms:config:vendormanagement:vg",
  VENDOR_DISTRIBUTION_SCHEDULE: "srn:vms:config:vendormanagement:vds",
  VENDOR_COMPLIANCE_DOCUMENT: "srn:vms:config:vendormanagement:vcd",
  VENDOR_COMPLIANCE_DOCUMENT_GROUP: "srn:vms:config:vendormanagement:vcdg"
};

export const Actions = {
  CREATE: "C",
  READ: "R",
  UPDATE: "U",
  DELETE: "D",
  REASSIGN: "RA",
};
