export enum NotificationEventCode {
    JOB_APPROVAL_FIRST = "JOB_APPROVAL_FIRST",
    JOB_REVIEW_FIRST = "JOB_REVIEW_FIRST",
    JOB_UPDATE_REVIEW = "JOB_UPDATE_REVIEW",
    JOB_UPDATE_APPROVAL = "JOB_UPDATE_APPROVAL",
    OFFER_REVIEW_FIRST = "OFFER_REVIEW_FIRST",
    OFFER_APPROVAL_FIRST = "OFFER_APPROVAL_FIRST",
    COUNTER_OFFER_REVIEW_FIRST = "COUNTER_OFFER_REVIEW_FIRST",
    COUNTER_OFFER_APPROVAL_FIRST = "COUNTER_OFFER_APPROVAL_FIRST",
    ASSIGNMENT_APPROVAL_REQUEST = "ASSIGNMENT_APPROVAL_REQUEST",
    ASSIGNMENT_MODIFIED_APPROVAL = "ASSIGNMENT_MODIFIED_APPROVAL",
    REHIRE_REVIEW = "REHIRE_REVIEW",
    DO_NOT_REHIRE_REVIEW = "DO_NOT_REHIRE_REVIEW",
    CANDIDATE_SHORTLIST_REQUEST_FIRST = "CANDIDATE_SHORTLIST_REQUEST_FIRST",
    RE_HIRE_APPROVAL = "RE_HIRE_APPROVAL",
    BUDGET_INCREASED_APPROVAL = "BUDGET_INCREASED_APPROVAL",
    BUDGET_REDUCED_APPROVAL = "BUDGET_REDUCED_APPROVAL",
    CUSTOMER_SUPPORT1 = "CUSTOMER_SUPPORT1"
}
