export interface InvoiceConfigInterface {
    id: string;
    program_id: string;
    name: string;
    slug: string;
    is_active: boolean;
    is_all_hierarchy_associate: boolean;
    hierarchy_ids: any;
    consolidation_type: 'manual' | 'automatic';
    consolidation_day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
    consolidation_cycle: 'daily' | 'weekly' | 'monthly';
    billing_period_start_day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
    consolidation_billing_period: 'daily' | 'weekly' | 'monthly';
    consolidate_till_date: boolean;
    consolidation_generation_time: string;
    rollup_group: 'hierarchy' | 'vendor' | 'program' | 'hierarchy_vendor';
    consolidated_start_number: number;
    batch_start_number: number;
    template_name: string;
    template_type: string;
    template_formats: string;
    invoice_from: object;
    invoice_to: object;
    payment_authorization_enable: boolean;
    rollback_enable: boolean;
    rollback_config: object;
    transaction_complete_enable: boolean;
    transaction_complete_type: 'manual' | 'automatic' | 'scheduled';
    transaction_complete_cycle: 'weekly' | 'daily';
    transaction_complete_start_day: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
    transaction_complete_time: string;
    transaction_complete_notes_enable: boolean;
    voucher_start_number: number;
    enable_timesheet_consolidation: boolean;
    enable_expense_consolidation: boolean;
    enable_misc_expense_consolidation: boolean;
    enable_cancel_consolidation: boolean;
    credit_debit: boolean;
    created_on?: bigint;
    updated_on?: bigint;
    created_by: string;
    updated_by: string;
    is_deleted: boolean;
}
