export interface TimesheetTypeConfigInterface {
  id?: string;
  title?: string;
  display_title?: string;
  program_id?: string;
  hierarchies?: { hierarchy_id: string }[];
  labor_categorys?: { labor_category_id: string }[];
  is_all_labor_category_associate?: boolean;
  work_period?: string;
  work_start_day?: string;
  timesheet_format?: string;
  time_format?: string;
  project?: any;
  allocations?: any;
  allow_non_billable_hours?: boolean;
  break?:any;
  timesheet_rounding?:any;
  notes?:any;
  st_per_week?: number;
  st_per_day?: number;
  st_days_per_week?: number;
  daily_limit?: any;
  weekly_limit?: any;
  weekend?: any;
  modification_rules?:any;
  thresholds?:any;
  copy_timesheet?:any;
  is_overnight_allowed?: boolean;
  soft_delete?: any;
  allow_timesheet_to_be_submitted?: string;
  is_enabled?: boolean;
  created_on?: number;
  modified_on?: number;
  created_by?: string;
  modified_by?: string;
  is_deleted?: boolean;
}
