export interface WorkflowData {
    id: string,
    name: string,
    event_id: string,
    method_id: string,
    hierarchies: any[],
    placement_order: number,
    module: string,
    config: any,
    is_enabled: boolean,
    levels: any[],
    initialTrigger: any[],
    created_on: Date,
    modified_on: Date,
    created_by: string,
    modified_by: string,
    program_id: string,
    is_deleted: boolean,
    workflow_id: string,
    flow_count: number,
    flow_type:string
}
